//! Slave-side dial configuration and state files under `<state>/dial/<name>/`.
//!
//! `config.json` is written by `herdr machine dial setup` and read by
//! `herdr machine dial run`; `state.json` is runtime state written by the
//! running dialer on transitions and read by `list`/`status`. Both live in a
//! private (0700) directory owned by the effective user, and are only read
//! when they are regular files private to that user.

use std::io::{self, Write as _};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use serde::{Deserialize, Serialize};

use super::status::{ErrorRecord, SlaveInfo};
use crate::client::endpoint::ProfileId;

pub(crate) const DIAL_CONFIG_VERSION: u32 = 1;
pub(crate) const DIAL_STATE_VERSION: u32 = 1;
/// Directory under the state dir holding one subdirectory per dial name.
pub(crate) const DIAL_DIR_NAME: &str = "dial";
pub(crate) const CONFIG_FILE_NAME: &str = "config.json";
pub(crate) const STATE_FILE_NAME: &str = "state.json";
/// Held (flock) by a running `herdr machine dial run <name>`.
pub(crate) const RUN_LOCK_FILE_NAME: &str = "run.lock";
/// Key generated by `setup` when no identity is configured.
pub(crate) const IDENTITY_FILE_NAME: &str = "id_ed25519";
pub(crate) const MAX_DIAL_FILE_BYTES: usize = 64 * 1024;
const MAX_HUB_BYTES: usize = 1024;
const MAX_IDENTITY_PATH_BYTES: usize = 4096;
const MAX_PUBLIC_KEY_BYTES: usize = 16 * 1024;
/// OpenSSH binds `ControlPath + "." + 16 random characters` before renaming
/// it into place, so a control path needs this much spare room.
const CONTROL_SOCKET_STAGING_BYTES: usize = 17;
/// Largest control socket index the dialer uses (its master pool size).
const MAX_CONTROL_SOCKET_INDEX: usize = 9;
static NEXT_TEMP_FILE: AtomicU64 = AtomicU64::new(1);

fn default_compression() -> bool {
    true
}

/// `<state>/dial`.
pub(crate) fn dial_root() -> PathBuf {
    crate::config::state_dir().join(DIAL_DIR_NAME)
}

/// Filesystem layout of one named dial link.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct DialPaths {
    pub(crate) name: String,
    /// Private (0700) directory `<root>/<name>/`.
    pub(crate) dir: PathBuf,
    pub(crate) config_file: PathBuf,
    pub(crate) state_file: PathBuf,
    pub(crate) lock_file: PathBuf,
    /// Default generated identity (`id_ed25519`, with `id_ed25519.pub`).
    pub(crate) identity_file: PathBuf,
}

impl DialPaths {
    /// Layout of `name` under `root`. `name` must already be validated with
    /// [`validate_dial_name`].
    pub(crate) fn new(root: &Path, name: &str) -> Self {
        let dir = root.join(name);
        Self {
            name: name.to_string(),
            config_file: dir.join(CONFIG_FILE_NAME),
            state_file: dir.join(STATE_FILE_NAME),
            lock_file: dir.join(RUN_LOCK_FILE_NAME),
            identity_file: dir.join(IDENTITY_FILE_NAME),
            dir,
        }
    }

    pub(crate) fn public_key_file(identity: &Path) -> PathBuf {
        let mut path = identity.as_os_str().to_owned();
        path.push(".pub");
        PathBuf::from(path)
    }
}

/// The first line of `<identity>.pub`, if it is a short single printable line.
pub(crate) fn read_public_key_line(identity: &Path) -> Option<String> {
    let file = std::fs::File::open(DialPaths::public_key_file(identity)).ok()?;
    let content = match crate::platform::read_limited_reader(file, MAX_PUBLIC_KEY_BYTES).ok()? {
        crate::platform::LimitedRead::Complete(content) => content,
        _ => return None,
    };
    let text = String::from_utf8(content).ok()?;
    let line = text.lines().next()?.trim();
    (!line.is_empty() && !line.chars().any(char::is_control)).then(|| line.to_string())
}

/// Validates a dial name with the session-name rules.
pub(crate) fn validate_dial_name(name: &str) -> Result<(), String> {
    crate::session::validate_name(name).map_err(|error| error.replace("session name", "dial name"))
}

/// Validates the SSH destination of the hub.
pub(crate) fn validate_hub(hub: &str) -> Result<(), String> {
    if hub.is_empty() {
        return Err("hub ssh target cannot be empty".into());
    }
    crate::remote::validate_remote_target(hub).map_err(|error| error.replace("--remote", "hub"))?;
    if hub.len() > MAX_HUB_BYTES {
        return Err(format!(
            "hub ssh target cannot be longer than {MAX_HUB_BYTES} bytes"
        ));
    }
    if hub.chars().any(|ch| ch.is_control() || ch.is_whitespace()) {
        return Err("hub ssh target cannot contain whitespace or control characters".into());
    }
    Ok(())
}

/// `config.json` of one dial link.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DialConfig {
    pub(crate) version: u32,
    pub(crate) name: String,
    /// SSH destination of the hub (`user@host`, an ssh_config alias, ...).
    pub(crate) hub: String,
    /// Dial-in machine id assigned by the hub (`herdr machine add --dial-in`).
    pub(crate) link_id: ProfileId,
    /// Absolute private key path; `None` uses OpenSSH's defaults/agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) identity_file: Option<PathBuf>,
    #[serde(default = "default_compression")]
    pub(crate) compression: bool,
    /// Fields written by newer versions; preserved on rewrite.
    #[serde(flatten)]
    pub(crate) extra: serde_json::Map<String, serde_json::Value>,
}

impl DialConfig {
    pub(crate) fn new(
        name: impl Into<String>,
        hub: impl Into<String>,
        link_id: ProfileId,
        identity_file: Option<PathBuf>,
        compression: bool,
    ) -> Result<Self, String> {
        let config = Self {
            version: DIAL_CONFIG_VERSION,
            name: name.into(),
            hub: hub.into(),
            link_id,
            identity_file,
            compression,
            extra: serde_json::Map::new(),
        };
        config.validate()?;
        Ok(config)
    }

    pub(crate) fn validate(&self) -> Result<(), String> {
        if self.version != DIAL_CONFIG_VERSION {
            return Err(format!(
                "unsupported dial config version {}; expected {DIAL_CONFIG_VERSION}",
                self.version
            ));
        }
        validate_dial_name(&self.name)?;
        validate_hub(&self.hub)?;
        ProfileId::parse(self.link_id.as_str())
            .map_err(|_| "link id must be 32 lowercase hexadecimal characters".to_string())?;
        if let Some(identity) = &self.identity_file {
            validate_identity_path(identity)?;
        }
        Ok(())
    }
}

/// Identity paths are absolute UTF-8 paths without control characters (they
/// are handed to `ssh -i` and printed).
pub(crate) fn validate_identity_path(path: &Path) -> Result<(), String> {
    let Some(text) = path.to_str() else {
        return Err("identity file path must be valid UTF-8".into());
    };
    if !path.is_absolute() {
        return Err("identity file path must be absolute".into());
    }
    if text.len() > MAX_IDENTITY_PATH_BYTES {
        return Err(format!(
            "identity file path cannot be longer than {MAX_IDENTITY_PATH_BYTES} bytes"
        ));
    }
    if text.chars().any(char::is_control) {
        return Err("identity file path cannot contain control characters".into());
    }
    Ok(())
}

/// Lifecycle state of a dialer, as reported in `state.json`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(crate) enum DialRunState {
    Connecting,
    Connected,
    Backoff,
    Stopped,
    #[serde(other)]
    Unknown,
}

impl DialRunState {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Connecting => "connecting",
            Self::Connected => "connected",
            Self::Backoff => "backoff",
            Self::Stopped => "stopped",
            Self::Unknown => "unknown",
        }
    }
}

/// `state.json` of one dial link (runtime state, written on transitions).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DialState {
    pub(crate) version: u32,
    pub(crate) state: DialRunState,
    #[serde(default)]
    pub(crate) since_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) last_error: Option<ErrorRecord>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) next_attempt_ms: Option<u64>,
    /// Process id of the dialer that wrote this state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) pid: Option<u32>,
    /// Facts the hub's acceptor reported in its hello (sanitized).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) hub: Option<SlaveInfo>,
}

impl DialState {
    pub(crate) fn new(state: DialRunState) -> Self {
        Self {
            version: DIAL_STATE_VERSION,
            state,
            since_ms: super::status::now_ms(),
            last_error: None,
            next_attempt_ms: None,
            pid: Some(std::process::id()),
            hub: None,
        }
    }
}

/// Loads `config.json`. `Ok(None)` when it does not exist. The file must be
/// a regular file owned by the effective user and not writable by others.
pub(crate) fn load_config(path: &Path) -> Result<Option<DialConfig>, String> {
    let Some(content) = read_private_file(path)
        .map_err(|error| format!("failed to read dial config {}: {error}", path.display()))?
    else {
        return Ok(None);
    };
    let config: DialConfig = serde_json::from_slice(&content)
        .map_err(|error| format!("dial config {} is invalid: {error}", path.display()))?;
    config
        .validate()
        .map_err(|error| format!("dial config {} is invalid: {error}", path.display()))?;
    Ok(Some(config))
}

/// Validates and durably stores `config.json` (private temp file, fsync,
/// rename, parent fsync).
pub(crate) fn store_config(path: &Path, config: &DialConfig) -> Result<(), String> {
    config.validate()?;
    let mut content = serde_json::to_vec_pretty(config).map_err(|error| error.to_string())?;
    content.push(b'\n');
    write_private_file(path, &content, true)
        .map_err(|error| format!("failed to write dial config {}: {error}", path.display()))
}

/// Reads `state.json`. `Ok(None)` when it does not exist.
pub(crate) fn read_state(path: &Path) -> io::Result<Option<DialState>> {
    let Some(content) = read_private_file(path)? else {
        return Ok(None);
    };
    serde_json::from_slice(&content)
        .map(Some)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))
}

/// Atomically replaces `state.json`. Runtime state: no fsync.
pub(crate) fn write_state(path: &Path, state: &DialState) -> io::Result<()> {
    let mut content = serde_json::to_vec_pretty(state).map_err(io::Error::other)?;
    content.push(b'\n');
    write_private_file(path, &content, false)
}

/// Names of configured dial links under `root` (valid names of directories
/// only), sorted. A missing root has none.
pub(crate) fn list_dial_names(root: &Path) -> io::Result<Vec<String>> {
    let entries = match std::fs::read_dir(root) {
        Ok(entries) => entries,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(error),
    };
    let mut names = Vec::new();
    for entry in entries {
        let entry = entry?;
        let Ok(name) = entry.file_name().into_string() else {
            continue;
        };
        if validate_dial_name(&name).is_err() {
            continue;
        }
        if entry.file_type().is_ok_and(|kind| kind.is_dir()) {
            names.push(name);
        }
    }
    names.sort();
    Ok(names)
}

pub(super) fn read_private_file(path: &Path) -> io::Result<Option<Vec<u8>>> {
    match crate::platform::file_is_private_to_current_user(path) {
        Ok(true) => {}
        Ok(false) => {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "refusing to read a file that is not a regular file private to the current user",
            ))
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    }
    let file = match std::fs::File::open(path) {
        Ok(file) => file,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    match crate::platform::read_limited_reader(file, MAX_DIAL_FILE_BYTES)? {
        crate::platform::LimitedRead::Complete(content) => Ok(Some(content)),
        crate::platform::LimitedRead::Empty => {
            Err(io::Error::new(io::ErrorKind::InvalidData, "file is empty"))
        }
        crate::platform::LimitedRead::Oversized => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("file exceeds {MAX_DIAL_FILE_BYTES} bytes"),
        )),
    }
}

pub(super) fn write_private_file(path: &Path, content: &[u8], durable: bool) -> io::Result<()> {
    if content.len() > MAX_DIAL_FILE_BYTES {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("file exceeds {MAX_DIAL_FILE_BYTES} bytes"),
        ));
    }
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    if let Ok(metadata) = std::fs::symlink_metadata(path) {
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "refusing to replace a non-file path",
            ));
        }
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("dial");
    let sequence = NEXT_TEMP_FILE.fetch_add(1, Ordering::Relaxed);
    let temp_path = parent.join(format!(
        ".{file_name}-{}-{sequence}.tmp",
        std::process::id()
    ));
    let mut temp = crate::platform::create_private_state_file(&temp_path)?;
    let written = temp
        .write_all(content)
        .and_then(|()| if durable { temp.sync_all() } else { Ok(()) });
    drop(temp);
    if let Err(error) = written {
        let _ = std::fs::remove_file(&temp_path);
        return Err(error);
    }
    if let Err(error) = crate::platform::replace_file(&temp_path, path) {
        let _ = std::fs::remove_file(&temp_path);
        return Err(error);
    }
    if durable {
        crate::platform::sync_parent_directory(parent)?;
    }
    Ok(())
}

/// Where the dialer's OpenSSH control sockets live: `<dial dir>/ctl-<n>`, or
/// a short private fallback directory under `/tmp/herdr-dial-<uid>/` when the
/// dial directory is too deep for a Unix socket path.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ControlSockets {
    pub(crate) dir: PathBuf,
    prefix: String,
}

impl ControlSockets {
    /// Chooses (and creates, for the fallback) the control socket directory.
    pub(crate) fn for_dial(paths: &DialPaths) -> io::Result<Self> {
        let primary = Self {
            dir: paths.dir.clone(),
            prefix: String::new(),
        };
        if primary.fits() {
            return Ok(primary);
        }
        let uid = crate::platform::current_uid().ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::Unsupported,
                "dial-in links require Unix in this version of Herdr",
            )
        })?;
        let fallback = Self::fallback(Path::new("/tmp"), uid, &paths.dir);
        if !fallback.fits() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "no SSH control socket path fits the Unix socket length limit",
            ));
        }
        crate::platform::ensure_private_directory(&fallback.dir)?;
        crate::platform::verify_private_directory(&fallback.dir)?;
        Ok(fallback)
    }

    /// Every place this dial name may have left control sockets: the dial
    /// directory and, when it exists and is private, the `/tmp` fallback.
    pub(crate) fn all_for_dial(paths: &DialPaths) -> Vec<Self> {
        let mut all = vec![Self {
            dir: paths.dir.clone(),
            prefix: String::new(),
        }];
        if let Some(uid) = crate::platform::current_uid() {
            let fallback = Self::fallback(Path::new("/tmp"), uid, &paths.dir);
            if crate::platform::verify_private_directory(&fallback.dir).is_ok() {
                all.push(fallback);
            }
        }
        all
    }

    fn fallback(base: &Path, uid: u32, dial_dir: &Path) -> Self {
        use sha2::{Digest as _, Sha256};

        let digest = Sha256::digest(dial_dir.to_string_lossy().as_bytes());
        let prefix = digest[..6]
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        Self {
            dir: base.join(format!("herdr-dial-{uid}")),
            prefix: format!("{prefix}-"),
        }
    }

    pub(crate) fn path(&self, index: usize) -> PathBuf {
        self.dir.join(format!("{}ctl-{index}", self.prefix))
    }

    /// The agent forwarding relay socket; shorter than any control path.
    pub(crate) fn agent_socket(&self) -> PathBuf {
        self.dir.join(format!("{}agent.sock", self.prefix))
    }

    fn fits(&self) -> bool {
        let longest = self.path(MAX_CONTROL_SOCKET_INDEX);
        // OpenSSH 8.7 and later split `-o ControlPath=...` into words, so
        // the path must be one word without quotes or escapes.
        let one_word = longest.to_str().is_some_and(|text| {
            !text
                .chars()
                .any(|ch| ch.is_whitespace() || matches!(ch, '"' | '\'' | '\\' | '#'))
        });
        if !one_word {
            return false;
        }
        let mut staging = longest.into_os_string();
        staging.push(".".repeat(CONTROL_SOCKET_STAGING_BYTES));
        crate::platform::local_socket_path_fits(Path::new(&staging))
    }

    /// Removes a leftover control socket (or file) at `index`.
    pub(crate) fn remove(&self, index: usize) {
        let path = self.path(index);
        if let Ok(metadata) = std::fs::symlink_metadata(&path) {
            if !metadata.is_dir() {
                let _ = std::fs::remove_file(&path);
            }
        }
    }
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        static NEXT: AtomicU64 = AtomicU64::new(1);
        let dir = std::env::temp_dir().join(format!(
            "herdr-dial-config-{}-{}-{name}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        crate::platform::ensure_private_directory(&dir).unwrap();
        dir
    }

    fn id() -> ProfileId {
        ProfileId::parse("0123456789abcdef0123456789abcdef").unwrap()
    }

    #[test]
    fn config_round_trips_and_preserves_unknown_fields() {
        let dir = scratch("config");
        let path = dir.join(CONFIG_FILE_NAME);
        assert_eq!(load_config(&path).unwrap(), None);

        let config = DialConfig::new(
            "laptop",
            "me@hub.example",
            id(),
            Some(PathBuf::from("/home/me/.ssh/id_herdr")),
            false,
        )
        .unwrap();
        store_config(&path, &config).unwrap();
        assert_eq!(load_config(&path).unwrap(), Some(config.clone()));
        {
            use std::os::unix::fs::MetadataExt;
            assert_eq!(std::fs::metadata(&path).unwrap().mode() & 0o777, 0o600);
        }

        let mut value: serde_json::Value =
            serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
        value["future"] = serde_json::json!({"x": 1});
        value.as_object_mut().unwrap().remove("compression");
        std::fs::write(&path, serde_json::to_vec(&value).unwrap()).unwrap();
        let loaded = load_config(&path).unwrap().unwrap();
        assert!(loaded.compression, "compression defaults to on");
        assert_eq!(loaded.extra["future"], serde_json::json!({"x": 1}));
        store_config(&path, &loaded).unwrap();
        let rewritten: serde_json::Value =
            serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
        assert_eq!(rewritten["future"], serde_json::json!({"x": 1}));

        let leftovers = std::fs::read_dir(&dir)
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| entry.file_name().to_string_lossy().ends_with(".tmp"))
            .count();
        assert_eq!(leftovers, 0);
    }

    #[test]
    fn config_validation_rejects_bad_fields() {
        assert!(DialConfig::new("ok", "hub", id(), None, true).is_ok());
        for (name, hub, identity) in [
            ("", "hub", None),
            ("bad name", "hub", None),
            ("..", "hub", None),
            ("ok", "", None),
            ("ok", "-oProxyCommand=x", None),
            ("ok", "me@hub extra", None),
            ("ok", "hub\n", None),
            ("ok", "hub", Some(PathBuf::from("relative/key"))),
            ("ok", "hub", Some(PathBuf::from("/abs/\u{1b}key"))),
        ] {
            assert!(
                DialConfig::new(name, hub, id(), identity.clone(), true).is_err(),
                "{name:?} {hub:?} {identity:?}"
            );
        }
        let long_hub = "h".repeat(MAX_HUB_BYTES + 1);
        assert!(DialConfig::new("ok", long_hub, id(), None, true).is_err());

        let dir = scratch("invalid");
        let path = dir.join(CONFIG_FILE_NAME);
        for content in [
            "not json".to_string(),
            format!(
                "{{\"version\":2,\"name\":\"ok\",\"hub\":\"hub\",\"link_id\":\"{}\"}}",
                id()
            ),
            "{\"version\":1,\"name\":\"ok\",\"hub\":\"hub\",\"link_id\":\"XYZ\"}".to_string(),
            format!(
                "{{\"version\":1,\"name\":\"no/slash\",\"hub\":\"hub\",\"link_id\":\"{}\"}}",
                id()
            ),
        ] {
            std::fs::write(&path, &content).unwrap();
            assert!(load_config(&path).is_err(), "{content}");
        }
    }

    #[test]
    fn private_files_refuse_symlinks_and_shared_modes() {
        use std::os::unix::fs::PermissionsExt;

        let dir = scratch("private");
        let config = DialConfig::new("ok", "hub", id(), None, true).unwrap();
        let real = dir.join("real.json");
        store_config(&real, &config).unwrap();

        let link = dir.join(CONFIG_FILE_NAME);
        std::os::unix::fs::symlink(&real, &link).unwrap();
        assert!(load_config(&link).is_err());
        assert!(store_config(&link, &config).is_err());

        std::fs::set_permissions(&real, std::fs::Permissions::from_mode(0o666)).unwrap();
        assert!(load_config(&real).is_err());

        let oversized = dir.join("big.json");
        std::fs::write(&oversized, vec![b' '; MAX_DIAL_FILE_BYTES + 1]).unwrap();
        std::fs::set_permissions(&oversized, std::fs::Permissions::from_mode(0o600)).unwrap();
        assert!(load_config(&oversized).is_err());
    }

    #[test]
    fn state_round_trips_and_tolerates_unknown_states() {
        let dir = scratch("state");
        let path = dir.join(STATE_FILE_NAME);
        assert_eq!(read_state(&path).unwrap(), None);

        let mut state = DialState::new(DialRunState::Backoff);
        state.last_error = Some(ErrorRecord::new("link_busy", "another dialer"));
        state.next_attempt_ms = Some(state.since_ms + 300_000);
        state.hub = Some(SlaveInfo {
            herdr_version: Some("0.9.0".into()),
            ..SlaveInfo::default()
        });
        write_state(&path, &state).unwrap();
        assert_eq!(read_state(&path).unwrap(), Some(state));

        for (raw, expected) in [
            ("connecting", DialRunState::Connecting),
            ("connected", DialRunState::Connected),
            ("stopped", DialRunState::Stopped),
            ("hibernating", DialRunState::Unknown),
        ] {
            std::fs::write(
                &path,
                format!("{{\"version\":1,\"state\":\"{raw}\",\"extra\":true}}"),
            )
            .unwrap();
            let state = read_state(&path).unwrap().unwrap();
            assert_eq!(state.state, expected);
            assert_eq!(state.since_ms, 0);
            assert_eq!(state.last_error, None);
        }
        std::fs::write(&path, "{\"state\":\"connected\"}").unwrap();
        assert_eq!(
            read_state(&path).unwrap_err().kind(),
            io::ErrorKind::InvalidData
        );
    }

    #[test]
    fn dial_names_are_listed_sorted_and_filtered() {
        let root = scratch("root");
        assert!(list_dial_names(&root.join("missing")).unwrap().is_empty());
        for name in ["work", "alpha", ".hidden-ok", "bad name"] {
            std::fs::create_dir_all(root.join(name)).unwrap();
        }
        std::fs::write(root.join("plain-file"), b"x").unwrap();
        assert_eq!(
            list_dial_names(&root).unwrap(),
            vec![".hidden-ok", "alpha", "work"]
        );
        let paths = DialPaths::new(&root, "work");
        assert_eq!(paths.dir, root.join("work"));
        assert_eq!(paths.config_file, root.join("work/config.json"));
        assert_eq!(paths.state_file, root.join("work/state.json"));
        assert_eq!(paths.identity_file, root.join("work/id_ed25519"));
        assert_eq!(
            DialPaths::public_key_file(&paths.identity_file),
            root.join("work/id_ed25519.pub")
        );
        assert!(validate_dial_name("bad name")
            .unwrap_err()
            .contains("dial name"));
    }

    #[test]
    fn public_key_line_is_read_from_the_pub_file() {
        let dir = scratch("pubkey");
        let identity = dir.join("id");
        assert_eq!(read_public_key_line(&identity), None);
        std::fs::write(
            dir.join("id.pub"),
            "ssh-ed25519 AAAA herdr-dial:x\nsecond line\n",
        )
        .unwrap();
        assert_eq!(
            read_public_key_line(&identity).as_deref(),
            Some("ssh-ed25519 AAAA herdr-dial:x")
        );
        std::fs::write(dir.join("id.pub"), "ssh-ed25519 AA\u{1b}AA\n").unwrap();
        assert_eq!(read_public_key_line(&identity), None);
        std::fs::write(dir.join("id.pub"), "\n").unwrap();
        assert_eq!(read_public_key_line(&identity), None);
    }

    #[test]
    fn control_sockets_fall_back_to_a_short_private_directory() {
        let root = scratch("ctl");
        let paths = DialPaths::new(&root, "short");
        let sockets = ControlSockets::for_dial(&paths).unwrap();
        assert_eq!(sockets.dir, paths.dir);
        assert_eq!(sockets.path(2), paths.dir.join("ctl-2"));
        assert_eq!(ControlSockets::all_for_dial(&paths)[0], sockets);
        assert_eq!(sockets.agent_socket(), paths.dir.join("agent.sock"));

        let deep = PathBuf::from("/").join("d".repeat(120)).join("dial");
        let deep_paths = DialPaths::new(&deep, "name");
        let fallback = ControlSockets::fallback(Path::new("/tmp"), 1234, &deep_paths.dir);
        assert_eq!(fallback.dir, Path::new("/tmp/herdr-dial-1234"));
        let name = fallback.path(0);
        let name = name.file_name().unwrap().to_string_lossy().into_owned();
        assert!(name.ends_with("-ctl-0"), "{name}");
        assert_eq!(name.len(), 12 + "-ctl-0".len());
        assert!(crate::platform::local_socket_path_fits(
            &fallback.agent_socket()
        ));
        assert!(fallback.fits());
        assert!(!ControlSockets {
            dir: deep_paths.dir.clone(),
            prefix: String::new()
        }
        .fits());
        assert_ne!(
            fallback.prefix,
            ControlSockets::fallback(Path::new("/tmp"), 1234, &paths.dir).prefix
        );
        // A path OpenSSH would split or unquote, such as one under
        // `~/Library/Application Support`, uses the fallback too.
        for dir in [
            "/Users/me/Library/Application Support/herdr/dial/work",
            "/s/\"q\"/dial",
            "/s/it's/dial",
            "/s/a\\b/dial",
            "/s/#1/dial",
        ] {
            let sockets = ControlSockets {
                dir: PathBuf::from(dir),
                prefix: String::new(),
            };
            assert!(!sockets.fits(), "{dir}");
        }

        crate::platform::ensure_private_directory(&paths.dir).unwrap();
        std::fs::write(sockets.path(1), b"stale").unwrap();
        sockets.remove(1);
        assert!(!sockets.path(1).exists());
    }
}
